package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

func (c *DynamORMMigrateCommand) generateMigrationCode(analysis *TableAnalysis, config *MigrationConfig) error {
	// Generate model
	if err := c.generateMigrationModel(analysis, config); err != nil {
		return fmt.Errorf("failed to generate model: %w", err)
	}

	// Generate CDK construct
	if err := c.generateMigrationCDK(analysis, config); err != nil {
		return fmt.Errorf("failed to generate CDK: %w", err)
	}

	// Generate migration script
	if err := c.generateMigrationScript(analysis, config); err != nil {
		return fmt.Errorf("failed to generate migration script: %w", err)
	}

	// Generate tests if requested
	if config.GenerateTests {
		if err := c.generateMigrationTests(analysis, config); err != nil {
			return fmt.Errorf("failed to generate tests: %w", err)
		}
	}

	return nil
}

func (c *DynamORMMigrateCommand) generateMigrationModel(analysis *TableAnalysis, config *MigrationConfig) error {
	tmpl := `// Generated by lift dynamorm migrate
// Source table: {{.TableName}}
// Generated at: {{.CreatedAt.Format "2006-01-02 15:04:05"}}

package models

import (
	"time"

	"github.com/pay-theory/lift/pkg/dynamorm"
)

// {{.ModelName}} represents the migrated {{.TableName}} entity
type {{.ModelName}} struct {
	{{if .IsMultiTenant}}{{.PartitionKey.Name}} string ` + "`" + `json:"{{.PartitionKey.Name | ToSnakeCase}}" dynamodb:"{{.PartitionKey.Name}},pk"` + "`" + `
	{{if .SortKey}}{{.SortKey.Name}} string ` + "`" + `json:"{{.SortKey.Name | ToSnakeCase}}" dynamodb:"{{.SortKey.Name}}"` + "`" + `
	{{end}}{{else}}{{.PartitionKey.Name}} string ` + "`" + `json:"{{.PartitionKey.Name | ToSnakeCase}}" dynamodb:"{{.PartitionKey.Name}},pk"` + "`" + `
	{{if .SortKey}}{{.SortKey.Name}} string ` + "`" + `json:"{{.SortKey.Name | ToSnakeCase}}" dynamodb:"{{.SortKey.Name}}"` + "`" + `
	{{end}}{{end}}

	// Common fields
	CreatedAt time.Time ` + "`" + `json:"created_at" dynamodb:"created_at"` + "`" + `
	UpdatedAt time.Time ` + "`" + `json:"updated_at" dynamodb:"updated_at"` + "`" + `

	{{if .TimeToLiveSpec}}// TTL field
	{{.TimeToLiveSpec.AttributeName}} int64 ` + "`" + `json:"{{.TimeToLiveSpec.AttributeName | ToSnakeCase}}" dynamodb:"{{.TimeToLiveSpec.AttributeName}}"` + "`" + `
	{{end}}

	{{range .GlobalSecondaryIndexes}}// GSI fields for {{.IndexName}}
	{{.PartitionKey.Name}} string ` + "`" + `json:"{{.PartitionKey.Name | ToSnakeCase}}" dynamodb:"{{.PartitionKey.Name}}" gsi:"{{.IndexName}}"` + "`" + `
	{{if .SortKey}}{{.SortKey.Name}} string ` + "`" + `json:"{{.SortKey.Name | ToSnakeCase}}" dynamodb:"{{.SortKey.Name}}" gsi:"{{.IndexName}}"` + "`" + `
	{{end}}{{end}}
}

// New{{.ModelName}} creates a new {{.ModelName}} instance
func New{{.ModelName}}({{if .IsMultiTenant}}{{.PartitionKey.Name | ToSnakeCase}} string{{if .SortKey}}, {{.SortKey.Name | ToSnakeCase}} string{{end}}{{else}}{{.PartitionKey.Name | ToSnakeCase}} string{{if .SortKey}}, {{.SortKey.Name | ToSnakeCase}} string{{end}}{{end}}) *{{.ModelName}} {
	now := time.Now()

	return &{{.ModelName}}{
		{{.PartitionKey.Name}}: {{.PartitionKey.Name | ToSnakeCase}},
		{{if .SortKey}}{{.SortKey.Name}}: {{.SortKey.Name | ToSnakeCase}},
		{{end}}CreatedAt: now,
		UpdatedAt: now,
		{{if .TimeToLiveSpec}}{{.TimeToLiveSpec.AttributeName}}: now.Add(24 * time.Hour).Unix(),
		{{end}}
	}
}

// TableName returns the DynamoDB table name
func (m *{{.ModelName}}) TableName() string {
	return "{{.TableName}}"
}

// Update updates the {{.ModelName}} timestamp
func (m *{{.ModelName}}) Update() {
	m.UpdatedAt = time.Now()
	{{if .TimeToLiveSpec}}m.{{.TimeToLiveSpec.AttributeName}} = time.Now().Add(24 * time.Hour).Unix()
	{{end}}
}
`

	data := struct {
		*TableAnalysis
		ModelName     string
		IsMultiTenant bool
	}{
		TableAnalysis: analysis,
		ModelName:     config.ModelName,
		IsMultiTenant: config.MultiTenant,
	}

	funcMap := template.FuncMap{
		"ToSnakeCase": func(s string) string {
			return strings.ToLower(strings.ReplaceAll(s, "-", "_"))
		},
	}

	t, err := template.New("model").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return err
	}

	filename := filepath.Join(config.OutputDir, strings.ToLower(config.ModelName)+".go")
	file, err := os.Create(filename) // #nosec G304 - filename is constructed from sanitized input in controlled directories
	if err != nil {
		return err
	}
	defer func() {
		if err := file.Close(); err != nil {
			fmt.Printf("Warning: failed to close file: %v\n", err)
		}
	}()

	return t.Execute(file, data)
}

func (c *DynamORMMigrateCommand) generateMigrationCDK(analysis *TableAnalysis, config *MigrationConfig) error {
	tmpl := `// Generated by lift dynamorm migrate
// Source table: {{.TableName}}
// Generated at: {{.CreatedAt.Format "2006-01-02 15:04:05"}}

package constructs

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsdynamodb"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/jsii-runtime-go"

	"github.com/pay-theory/lift/pkg/cdk/constructs"
)

// {{.ModelName}}TableProps defines the properties for the migrated {{.ModelName}} table
type {{.ModelName}}TableProps struct {
	// DynamORM Table Props
	*constructs.DynamORMTableProps

	// Migration-specific settings
	EnableMigrationMode  *bool
	OriginalTableName    *string
	BackupTableName      *string
}

// {{.ModelName}}Table represents the migrated DynamoDB table for {{.ModelName}} entities
type {{.ModelName}}Table struct {
	constructs.Construct
	DynamORMTable *constructs.DynamORMTable
}

// New{{.ModelName}}Table creates a new {{.ModelName}} table construct from migration
func New{{.ModelName}}Table(scope constructs.Construct, id *string, props *{{.ModelName}}TableProps) *{{.ModelName}}Table {
	this := &{{.ModelName}}Table{}
	this.Construct = constructs.NewConstruct(scope, id)

	// Set defaults from analysis
	if props.DynamORMTableProps == nil {
		props.DynamORMTableProps = &constructs.DynamORMTableProps{}
	}

	if props.DynamORMTableProps.TableName == nil {
		props.DynamORMTableProps.TableName = jsii.String("{{.TableName}}")
	}

	if props.OriginalTableName == nil {
		props.OriginalTableName = jsii.String("{{.TableName}}")
	}

	// Configure table structure based on analysis
	props.DynamORMTableProps.PartitionKey = &awsdynamodb.Attribute{
		Name: jsii.String("{{.PartitionKey.Name}}"),
		Type: awsdynamodb.AttributeType_{{.PartitionKey.Type | ToDynamoType}},
	}

	{{if .SortKey}}props.DynamORMTableProps.SortKey = &awsdynamodb.Attribute{
		Name: jsii.String("{{.SortKey.Name}}"),
		Type: awsdynamodb.AttributeType_{{.SortKey.Type | ToDynamoType}},
	}
	{{end}}

	// Configure TTL if present
	{{if .TimeToLiveSpec}}props.DynamORMTableProps.TimeToLiveAttribute = jsii.String("{{.TimeToLiveSpec.AttributeName}}")
	{{end}}

	// Configure streams if present
	{{if .StreamSpec}}props.DynamORMTableProps.Stream = awsdynamodb.StreamViewType_{{.StreamSpec.ViewType | ToStreamType}}
	{{end}}

	// Set multi-tenant mode
	{{if .IsMultiTenant}}props.DynamORMTableProps.EnableMultiTenant = jsii.Bool(true)
	{{end}}

	// Create the DynamORM table
	this.DynamORMTable = constructs.NewDynamORMTable(this, jsii.String("Table"), props.DynamORMTableProps)

	{{range .GlobalSecondaryIndexes}}// Add {{.IndexName}} GSI from migration
	this.DynamORMTable.AddGSI(&constructs.GSIProps{
		IndexName: jsii.String("{{.IndexName}}"),
		PartitionKey: &awsdynamodb.Attribute{
			Name: jsii.String("{{.PartitionKey.Name}}"),
			Type: awsdynamodb.AttributeType_{{.PartitionKey.Type | ToDynamoType}},
		},
		{{if .SortKey}}SortKey: &awsdynamodb.Attribute{
			Name: jsii.String("{{.SortKey.Name}}"),
			Type: awsdynamodb.AttributeType_{{.SortKey.Type | ToDynamoType}},
		},
		{{end}}ProjectionType: awsdynamodb.ProjectionType_{{.ProjectionType | ToProjectionType}},
	})
	{{end}}

	// Add migration-specific configurations
	if props.EnableMigrationMode != nil && *props.EnableMigrationMode {
		c.configureForMigration(this.DynamORMTable, props)
	}

	return this
}

// configureForMigration adds migration-specific settings
func (t *{{.ModelName}}Table) configureForMigration(table *constructs.DynamORMTable, props *{{.ModelName}}TableProps) {
	// Enable point-in-time recovery for safe migration
	table.Table.PointInTimeRecovery = jsii.Bool(true)

	// Add tags to identify migration
	table.Table.Tags().SetTag(jsii.String("MigrationSource"), props.OriginalTableName, jsii.Number(1))
	table.Table.Tags().SetTag(jsii.String("MigrationDate"), jsii.String("{{.CreatedAt.Format "2006-01-02"}}"), jsii.Number(1))
	table.Table.Tags().SetTag(jsii.String("DynamORMGenerated"), jsii.String("true"), jsii.Number(1))
}

// TableName returns the table name
func (t *{{.ModelName}}Table) TableName() *string {
	return t.DynamORMTable.Table.TableName()
}

// TableArn returns the table ARN
func (t *{{.ModelName}}Table) TableArn() *string {
	return t.DynamORMTable.Table.TableArn()
}

// GrantReadData grants read permissions to the table
func (t *{{.ModelName}}Table) GrantReadData(grantee awscdk.IPrincipal) {
	t.DynamORMTable.GrantReadData(grantee)
}

// GrantWriteData grants write permissions to the table
func (t *{{.ModelName}}Table) GrantWriteData(grantee awscdk.IPrincipal) {
	t.DynamORMTable.GrantWriteData(grantee)
}

// GrantFullAccess grants full access to the table
func (t *{{.ModelName}}Table) GrantFullAccess(grantee awscdk.IPrincipal) {
	t.DynamORMTable.GrantFullAccess(grantee)
}
`

	data := struct {
		*TableAnalysis
		ModelName     string
		IsMultiTenant bool
	}{
		TableAnalysis: analysis,
		ModelName:     config.ModelName,
		IsMultiTenant: config.MultiTenant,
	}

	funcMap := template.FuncMap{
		"ToDynamoType": func(s string) string {
			switch strings.ToLower(s) {
			case stringType:
				return "STRING"
			case "number":
				return "NUMBER"
			case "binary":
				return "BINARY"
			default:
				return "STRING"
			}
		},
		"ToStreamType": func(s string) string {
			switch strings.ToUpper(s) {
			case keysOnlyView:
				return keysOnlyView
			case "NEW_IMAGE":
				return "NEW_IMAGE"
			case "OLD_IMAGE":
				return "OLD_IMAGE"
			case newAndOldImagesView:
				return newAndOldImagesView
			default:
				return newAndOldImagesView
			}
		},
		"ToProjectionType": func(s string) string {
			switch strings.ToUpper(s) {
			case allView:
				return allView
			case keysOnlyView:
				return keysOnlyView
			case "INCLUDE":
				return "INCLUDE"
			default:
				return allView
			}
		},
	}

	t, err := template.New("cdk").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return err
	}

	filename := filepath.Join(config.OutputDir, strings.ToLower(config.ModelName)+"_table.go")
	file, err := os.Create(filename) // #nosec G304 - filename is constructed from sanitized input in controlled directories
	if err != nil {
		return err
	}
	defer func() {
		if err := file.Close(); err != nil {
			fmt.Printf("Warning: failed to close file: %v\n", err)
		}
	}()

	return t.Execute(file, data)
}

func (c *DynamORMMigrateCommand) generateMigrationScript(analysis *TableAnalysis, config *MigrationConfig) error {
	tmpl := `// Generated by lift dynamorm migrate
// Migration script for {{.TableName}} -> {{.ModelName}}
// Generated at: {{.CreatedAt.Format "2006-01-02 15:04:05"}}

package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	"github.com/pay-theory/lift/pkg/dynamorm"
)

// MigrationStats tracks migration progress
type MigrationStats struct {
	SourceTable      string    ` + "`" + `json:"source_table"` + "`" + `
	DestinationTable string    ` + "`" + `json:"destination_table"` + "`" + `
	StartTime        time.Time ` + "`" + `json:"start_time"` + "`" + `
	EndTime          time.Time ` + "`" + `json:"end_time"` + "`" + `
	TotalItems       int64     ` + "`" + `json:"total_items"` + "`" + `
	MigratedItems    int64     ` + "`" + `json:"migrated_items"` + "`" + `
	ErrorCount       int64     ` + "`" + `json:"error_count"` + "`" + `
	BatchSize        int32     ` + "`" + `json:"batch_size"` + "`" + `
	DryRun           bool      ` + "`" + `json:"dry_run"` + "`" + `
}

// MigrationConfig holds migration configuration
type MigrationConfig struct {
	SourceTableName      string
	DestinationTableName string
	Region               string
	BatchSize            int32
	DryRun               bool
	MaxConcurrency       int
	BackupBeforeMigration bool
	ValidateAfterMigration bool
}

func main() {
	// Parse command line arguments
	config := parseMigrationArgs()

	// Setup AWS client
	ctx := context.Background()
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(config.Region))
	if err != nil {
		log.Fatalf("Failed to load AWS config: %v", err)
	}

	client := dynamodb.NewFromConfig(cfg)

	// Initialize migration stats
	stats := &MigrationStats{
		SourceTable:      config.SourceTableName,
		DestinationTable: config.DestinationTableName,
		StartTime:        time.Now(),
		BatchSize:        config.BatchSize,
		DryRun:           config.DryRun,
	}

	fmt.Printf("🚀 Starting migration from %s to %s\n", config.SourceTableName, config.DestinationTableName)
	fmt.Printf("   • Batch Size: %d\n", config.BatchSize)
	fmt.Printf("   • Dry Run: %t\n", config.DryRun)
	fmt.Printf("   • Region: %s\n", config.Region)

	// Validate source table exists
	if err := validateSourceTable(ctx, client, config.SourceTableName); err != nil {
		log.Fatalf("Source table validation failed: %v", err)
	}

	// Create backup if requested
	if config.BackupBeforeMigration && !config.DryRun {
		if err := createBackup(ctx, client, config.SourceTableName); err != nil {
			log.Printf("⚠️  Backup creation failed (continuing): %v", err)
		} else {
			fmt.Printf("✅ Backup created for %s\n", config.SourceTableName)
		}
	}

	// Perform migration
	if err := performMigration(ctx, client, config, stats); err != nil {
		log.Fatalf("Migration failed: %v", err)
	}

	// Validate migration if requested
	if config.ValidateAfterMigration && !config.DryRun {
		if err := validateMigration(ctx, client, config, stats); err != nil {
			log.Printf("⚠️  Migration validation failed: %v", err)
		} else {
			fmt.Printf("✅ Migration validation passed\n")
		}
	}

	// Print final stats
	stats.EndTime = time.Now()
	printMigrationSummary(stats)
}

func parseMigrationArgs() *MigrationConfig {
	config := &MigrationConfig{
		SourceTableName:      "{{.TableName}}",
		DestinationTableName: "{{.TableName}}-migrated",
		Region:               "us-east-1",
		BatchSize:            25,
		DryRun:               false,
		MaxConcurrency:       4,
		BackupBeforeMigration: true,
		ValidateAfterMigration: true,
	}

	// Parse OS args (simple implementation)
	args := os.Args[1:]
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--source":
			if i+1 < len(args) {
				config.SourceTableName = args[i+1]
				i++
			}
		case "--destination":
			if i+1 < len(args) {
				config.DestinationTableName = args[i+1]
				i++
			}
		case "--region":
			if i+1 < len(args) {
				config.Region = args[i+1]
				i++
			}
		case "--dry-run":
			config.DryRun = true
		case "--no-backup":
			config.BackupBeforeMigration = false
		case "--no-validation":
			config.ValidateAfterMigration = false
		}
	}

	return config
}

func validateSourceTable(ctx context.Context, client *dynamodb.Client, tableName string) error {
	_, err := client.DescribeTable(ctx, &dynamodb.DescribeTableInput{
		TableName: aws.String(tableName),
	})
	if err != nil {
		return fmt.Errorf("source table %s not found: %w", tableName, err)
	}
	return nil
}

func createBackup(ctx context.Context, client *dynamodb.Client, tableName string) error {
	backupName := fmt.Sprintf("%s-migration-backup-%d", tableName, time.Now().Unix())

	_, err := client.CreateBackup(ctx, &dynamodb.CreateBackupInput{
		TableName:  aws.String(tableName),
		BackupName: aws.String(backupName),
	})

	return err
}

func performMigration(ctx context.Context, client *dynamodb.Client, config *MigrationConfig, stats *MigrationStats) error {
	// Get item count for progress tracking
	describeOutput, err := client.DescribeTable(ctx, &dynamodb.DescribeTableInput{
		TableName: aws.String(config.SourceTableName),
	})
	if err != nil {
		return fmt.Errorf("failed to describe source table: %w", err)
	}

	stats.TotalItems = *describeOutput.Table.ItemCount
	fmt.Printf("📊 Total items to migrate: %d\n", stats.TotalItems)

	// Scan and migrate items in batches
	var lastEvaluatedKey map[string]types.AttributeValue

	for {
		// Scan batch from source table
		scanInput := &dynamodb.ScanInput{
			TableName:                 aws.String(config.SourceTableName),
			Limit:                     aws.Int32(config.BatchSize),
			ExclusiveStartKey:         lastEvaluatedKey,
		}

		scanOutput, err := client.Scan(ctx, scanInput)
		if err != nil {
			return fmt.Errorf("failed to scan source table: %w", err)
		}

		if len(scanOutput.Items) == 0 {
			break
		}

		// Process batch
		if err := processBatch(ctx, client, config, scanOutput.Items, stats); err != nil {
			log.Printf("⚠️  Batch processing error: %v", err)
			stats.ErrorCount++
		} else {
			stats.MigratedItems += int64(len(scanOutput.Items))
		}

		// Progress update
		percentage := float64(stats.MigratedItems) / float64(stats.TotalItems) * 100
		fmt.Printf("🔄 Progress: %d/%d (%.1f%%)\n", stats.MigratedItems, stats.TotalItems, percentage)

		// Check if we need to continue
		lastEvaluatedKey = scanOutput.LastEvaluatedKey
		if lastEvaluatedKey == nil {
			break
		}

		// Small delay to avoid throttling
		time.Sleep(100 * time.Millisecond)
	}

	return nil
}

func processBatch(ctx context.Context, client *dynamodb.Client, config *MigrationConfig, items []map[string]types.AttributeValue, stats *MigrationStats) error {
	if config.DryRun {
		// In dry run mode, just log what would be done
		fmt.Printf("   [DRY RUN] Would migrate %d items\n", len(items))
		return nil
	}

	// Transform items for DynamORM compatibility
	transformedItems := make([]map[string]types.AttributeValue, len(items))
	for i, item := range items {
		transformedItems[i] = transformItem(item)
	}

	// Batch write to destination table
	writeRequests := make([]types.WriteRequest, len(transformedItems))
	for i, item := range transformedItems {
		writeRequests[i] = types.WriteRequest{
			PutRequest: &types.PutRequest{
				Item: item,
			},
		}
	}

	// Execute batch write
	_, err := client.BatchWriteItem(ctx, &dynamodb.BatchWriteItemInput{
		RequestItems: map[string][]types.WriteRequest{
			config.DestinationTableName: writeRequests,
		},
	})

	return err
}

func transformItem(item map[string]types.AttributeValue) map[string]types.AttributeValue {
	// Add DynamORM-specific fields
	transformed := make(map[string]types.AttributeValue)

	// Copy existing attributes
	for k, v := range item {
		transformed[k] = v
	}

	// Add timestamps if not present
	now := time.Now()
	if _, exists := transformed["created_at"]; !exists {
		transformed["created_at"] = &types.AttributeValueMemberS{
			Value: now.Format(time.RFC3339),
		}
	}

	if _, exists := transformed["updated_at"]; !exists {
		transformed["updated_at"] = &types.AttributeValueMemberS{
			Value: now.Format(time.RFC3339),
		}
	}

	return transformed
}

func validateMigration(ctx context.Context, client *dynamodb.Client, config *MigrationConfig, stats *MigrationStats) error {
	// Compare item counts
	sourceCount, err := getItemCount(ctx, client, config.SourceTableName)
	if err != nil {
		return fmt.Errorf("failed to get source item count: %w", err)
	}

	destCount, err := getItemCount(ctx, client, config.DestinationTableName)
	if err != nil {
		return fmt.Errorf("failed to get destination item count: %w", err)
	}

	fmt.Printf("📊 Validation Results:\n")
	fmt.Printf("   • Source Items: %d\n", sourceCount)
	fmt.Printf("   • Destination Items: %d\n", destCount)
	fmt.Printf("   • Difference: %d\n", sourceCount-destCount)

	if sourceCount != destCount {
		return fmt.Errorf("item count mismatch: source=%d, destination=%d", sourceCount, destCount)
	}

	return nil
}

func getItemCount(ctx context.Context, client *dynamodb.Client, tableName string) (int64, error) {
	describeOutput, err := client.DescribeTable(ctx, &dynamodb.DescribeTableInput{
		TableName: aws.String(tableName),
	})
	if err != nil {
		return 0, err
	}

	return *describeOutput.Table.ItemCount, nil
}

func printMigrationSummary(stats *MigrationStats) {
	duration := stats.EndTime.Sub(stats.StartTime)

	fmt.Printf("\n📋 Migration Summary:\n")
	fmt.Printf("   • Source Table: %s\n", stats.SourceTable)
	fmt.Printf("   • Destination Table: %s\n", stats.DestinationTable)
	fmt.Printf("   • Duration: %v\n", duration)
	fmt.Printf("   • Total Items: %d\n", stats.TotalItems)
	fmt.Printf("   • Migrated Items: %d\n", stats.MigratedItems)
	fmt.Printf("   • Error Count: %d\n", stats.ErrorCount)
	fmt.Printf("   • Success Rate: %.2f%%\n", float64(stats.MigratedItems)/float64(stats.TotalItems)*100)
	fmt.Printf("   • Items/Second: %.2f\n", float64(stats.MigratedItems)/duration.Seconds())
	fmt.Printf("   • Dry Run: %t\n", stats.DryRun)

	if stats.ErrorCount == 0 && stats.MigratedItems == stats.TotalItems {
		fmt.Printf("✅ Migration completed successfully!\n")
	} else {
		fmt.Printf("⚠️  Migration completed with %d errors\n", stats.ErrorCount)
	}
}
`

	data := struct {
		*TableAnalysis
		ModelName string
	}{
		TableAnalysis: analysis,
		ModelName:     config.ModelName,
	}

	t, err := template.New("migration").Parse(tmpl)
	if err != nil {
		return err
	}

	filename := filepath.Join(config.OutputDir, "migrate_"+strings.ToLower(config.ModelName)+".go")
	file, err := os.Create(filename) // #nosec G304 - filename is constructed from sanitized input in controlled directories
	if err != nil {
		return err
	}
	defer func() {
		if err := file.Close(); err != nil {
			fmt.Printf("Warning: failed to close file: %v\n", err)
		}
	}()

	return t.Execute(file, data)
}

func (c *DynamORMMigrateCommand) generateMigrationTests(analysis *TableAnalysis, config *MigrationConfig) error {
	tmpl := `// Generated by lift dynamorm migrate
// Tests for migrated {{.TableName}} -> {{.ModelName}}
// Generated at: {{.CreatedAt.Format "2006-01-02 15:04:05"}}

package models

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/pay-theory/lift/pkg/dynamorm"
	"github.com/pay-theory/lift/pkg/cdk/test"
)

func Test{{.ModelName}}_TableName(t *testing.T) {
	{{.ModelName | ToLowerCase}} := &{{.ModelName}}{}
	assert.Equal(t, "{{.TableName}}", {{.ModelName | ToLowerCase}}.TableName())
}

func Test{{.ModelName}}_New{{.ModelName}}(t *testing.T) {
	{{if .IsMultiTenant}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("tenant123"{{if .SortKey}}, "sort123"{{end}})

	assert.Equal(t, "tenant123", {{.ModelName | ToLowerCase}}.{{.PartitionKey.Name}})
	{{if .SortKey}}assert.Equal(t, "sort123", {{.ModelName | ToLowerCase}}.{{.SortKey.Name}}){{end}}{{else}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("pk123"{{if .SortKey}}, "sort123"{{end}})

	assert.Equal(t, "pk123", {{.ModelName | ToLowerCase}}.{{.PartitionKey.Name}})
	{{if .SortKey}}assert.Equal(t, "sort123", {{.ModelName | ToLowerCase}}.{{.SortKey.Name}}){{end}}{{end}}
	assert.False(t, {{.ModelName | ToLowerCase}}.CreatedAt.IsZero())
	assert.False(t, {{.ModelName | ToLowerCase}}.UpdatedAt.IsZero())
	{{if .TimeToLiveSpec}}assert.Greater(t, {{.ModelName | ToLowerCase}}.{{.TimeToLiveSpec.AttributeName}}, int64(0)){{end}}
}

func Test{{.ModelName}}_Update(t *testing.T) {
	{{if .IsMultiTenant}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("tenant123"{{if .SortKey}}, "sort123"{{end}}){{else}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("pk123"{{if .SortKey}}, "sort123"{{end}}){{end}}

	originalUpdatedAt := {{.ModelName | ToLowerCase}}.UpdatedAt
	{{if .TimeToLiveSpec}}originalTTL := {{.ModelName | ToLowerCase}}.{{.TimeToLiveSpec.AttributeName}}{{end}}

	// Wait a bit to ensure timestamp changes
	time.Sleep(10 * time.Millisecond)

	{{.ModelName | ToLowerCase}}.Update()

	assert.True(t, {{.ModelName | ToLowerCase}}.UpdatedAt.After(originalUpdatedAt))
	{{if .TimeToLiveSpec}}assert.Greater(t, {{.ModelName | ToLowerCase}}.{{.TimeToLiveSpec.AttributeName}}, originalTTL){{end}}
}

func Test{{.ModelName}}_DynamORMIntegration(t *testing.T) {
	// Setup test environment
	ctx := context.Background()

	// Use DynamORM test helpers
	db, cleanup := test.SetupDynamORMTest(t, "{{.TableName}}")
	defer cleanup()

	// Create test entity
	{{if .IsMultiTenant}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("test-tenant"{{if .SortKey}}, "test-sort"{{end}}){{else}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("test-pk"{{if .SortKey}}, "test-sort"{{end}}){{end}}
	{{.ModelName | ToLowerCase}}.Name = "Test {{.ModelName}}"

	// Test Put operation
	err := db.Put(ctx, {{.ModelName | ToLowerCase}})
	require.NoError(t, err)

	// Test Get operation
	var retrieved {{.ModelName}}
	{{if .IsMultiTenant}}err = db.GetByPK(ctx, "test-tenant"{{if .SortKey}}, "test-sort"{{end}}, &retrieved){{else}}err = db.GetByPK(ctx, "test-pk"{{if .SortKey}}, "test-sort"{{end}}, &retrieved){{end}}
	require.NoError(t, err)

	assert.Equal(t, {{.ModelName | ToLowerCase}}.{{.PartitionKey.Name}}, retrieved.{{.PartitionKey.Name}})
	{{if .SortKey}}assert.Equal(t, {{.ModelName | ToLowerCase}}.{{.SortKey.Name}}, retrieved.{{.SortKey.Name}}){{end}}
	assert.Equal(t, "Test {{.ModelName}}", retrieved.Name)

	// Test Update operation
	retrieved.Name = "Updated {{.ModelName}}"
	retrieved.Update()

	err = db.Put(ctx, &retrieved)
	require.NoError(t, err)

	// Verify update
	var updated {{.ModelName}}
	{{if .IsMultiTenant}}err = db.GetByPK(ctx, "test-tenant"{{if .SortKey}}, "test-sort"{{end}}, &updated){{else}}err = db.GetByPK(ctx, "test-pk"{{if .SortKey}}, "test-sort"{{end}}, &updated){{end}}
	require.NoError(t, err)
	assert.Equal(t, "Updated {{.ModelName}}", updated.Name)

	// Test Delete operation
	err = db.Delete(ctx, &updated)
	require.NoError(t, err)

	// Verify deletion
	var deleted {{.ModelName}}
	{{if .IsMultiTenant}}err = db.GetByPK(ctx, "test-tenant"{{if .SortKey}}, "test-sort"{{end}}, &deleted){{else}}err = db.GetByPK(ctx, "test-pk"{{if .SortKey}}, "test-sort"{{end}}, &deleted){{end}}
	assert.Error(t, err)
	assert.Equal(t, dynamorm.ErrNotFound, err)
}

{{range .GlobalSecondaryIndexes}}func Test{{$.ModelName}}_{{.IndexName}}GSI(t *testing.T) {
	ctx := context.Background()

	// Setup test environment
	db, cleanup := test.SetupDynamORMTest(t, "{{$.TableName}}")
	defer cleanup()

	// Create test entities with GSI attributes
	{{if $.IsMultiTenant}}entity1 := New{{$.ModelName}}("tenant1", "item1"){{else}}entity1 := New{{$.ModelName}}("pk1", "item1"){{end}}
	entity1.{{.PartitionKey.Name}} = "gsi-pk-1"
	{{if .SortKey}}entity1.{{.SortKey.Name}} = "gsi-sk-1"{{end}}

	{{if $.IsMultiTenant}}entity2 := New{{$.ModelName}}("tenant2", "item2"){{else}}entity2 := New{{$.ModelName}}("pk2", "item2"){{end}}
	entity2.{{.PartitionKey.Name}} = "gsi-pk-1"
	{{if .SortKey}}entity2.{{.SortKey.Name}} = "gsi-sk-2"{{end}}

	// Save entities
	require.NoError(t, db.Put(ctx, entity1))
	require.NoError(t, db.Put(ctx, entity2))

	// Query by GSI
	var results []{{$.ModelName}}
	err := db.Query(ctx, &results,
		dynamorm.WithIndex("{{.IndexName}}"),
		dynamorm.WithPartitionKey("gsi-pk-1"),
	)
	require.NoError(t, err)
	assert.Len(t, results, 2)
}
{{end}}

{{if .IsMultiTenant}}func Test{{.ModelName}}_MultiTenantIsolation(t *testing.T) {
	ctx := context.Background()

	// Setup test environment
	db, cleanup := test.SetupDynamORMTest(t, "{{.TableName}}")
	defer cleanup()

	// Create entities for different tenants
	tenant1Entity := New{{.ModelName}}("tenant1"{{if .SortKey}}, "item1"{{end}})
	tenant1Entity.Name = "Tenant 1 Item"

	tenant2Entity := New{{.ModelName}}("tenant2"{{if .SortKey}}, "item2"{{end}})
	tenant2Entity.Name = "Tenant 2 Item"

	// Save entities
	require.NoError(t, db.Put(ctx, tenant1Entity))
	require.NoError(t, db.Put(ctx, tenant2Entity))

	// Query tenant 1 items
	var tenant1Results []{{.ModelName}}
	err := db.Query(ctx, &tenant1Results, dynamorm.WithPartitionKey("tenant1"))
	require.NoError(t, err)
	assert.Len(t, tenant1Results, 1)
	assert.Equal(t, "Tenant 1 Item", tenant1Results[0].Name)

	// Query tenant 2 items
	var tenant2Results []{{.ModelName}}
	err = db.Query(ctx, &tenant2Results, dynamorm.WithPartitionKey("tenant2"))
	require.NoError(t, err)
	assert.Len(t, tenant2Results, 1)
	assert.Equal(t, "Tenant 2 Item", tenant2Results[0].Name)

	// Verify cross-tenant isolation
	var crossTenantResults []{{.ModelName}}
	err = db.Query(ctx, &crossTenantResults, dynamorm.WithPartitionKey("tenant1"))
	require.NoError(t, err)

	for _, result := range crossTenantResults {
		assert.Equal(t, "tenant1", result.{{.PartitionKey.Name}})
		assert.NotEqual(t, "tenant2", result.{{.PartitionKey.Name}})
	}
}
{{end}}

{{if .TimeToLiveSpec}}func Test{{.ModelName}}_TTLHandling(t *testing.T) {
	{{if .IsMultiTenant}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("tenant123"{{if .SortKey}}, "sort123"{{end}}){{else}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("pk123"{{if .SortKey}}, "sort123"{{end}}){{end}}

	// Test initial TTL is set
	assert.Greater(t, {{.ModelName | ToLowerCase}}.{{.TimeToLiveSpec.AttributeName}}, int64(0))

	// Test TTL is in the future
	futureTime := time.Now().Add(time.Hour).Unix()
	assert.LessOrEqual(t, {{.ModelName | ToLowerCase}}.{{.TimeToLiveSpec.AttributeName}}, futureTime)

	// Test Update refreshes TTL
	originalTTL := {{.ModelName | ToLowerCase}}.{{.TimeToLiveSpec.AttributeName}}
	time.Sleep(10 * time.Millisecond)
	{{.ModelName | ToLowerCase}}.Update()

	assert.Greater(t, {{.ModelName | ToLowerCase}}.{{.TimeToLiveSpec.AttributeName}}, originalTTL)
}
{{end}}

func Test{{.ModelName}}_StructTags(t *testing.T) {
	// Use reflection to verify struct tags are correct
	{{.ModelName | ToLowerCase}} := &{{.ModelName}}{}

	// This is a basic test - in practice you'd use reflection
	// to verify DynamoDB struct tags are properly set
	assert.NotNil(t, {{.ModelName | ToLowerCase}})

	// Verify table name is set correctly
	assert.Equal(t, "{{.TableName}}", {{.ModelName | ToLowerCase}}.TableName())
}

func Benchmark{{.ModelName}}_CRUD(b *testing.B) {
	ctx := context.Background()

	// Setup test environment
	db, cleanup := test.SetupDynamORMTest(nil, "{{.TableName}}")
	defer cleanup()

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		// Create
		{{if .IsMultiTenant}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}("tenant123", fmt.Sprintf("item%d", i)){{else}}{{.ModelName | ToLowerCase}} := New{{.ModelName}}(fmt.Sprintf("pk%d", i){{if .SortKey}}, fmt.Sprintf("sk%d", i){{end}}){{end}}

		// Put
		_ = db.Put(ctx, {{.ModelName | ToLowerCase}})

		// Get
		var retrieved {{.ModelName}}
		{{if .IsMultiTenant}}_ = db.GetByPK(ctx, "tenant123", fmt.Sprintf("item%d", i), &retrieved){{else}}_ = db.GetByPK(ctx, fmt.Sprintf("pk%d", i){{if .SortKey}}, fmt.Sprintf("sk%d", i){{end}}, &retrieved){{end}}

		// Update
		retrieved.Update()
		_ = db.Put(ctx, &retrieved)

		// Delete
		_ = db.Delete(ctx, &retrieved)
	}
}
`

	data := struct {
		*TableAnalysis
		ModelName     string
		IsMultiTenant bool
	}{
		TableAnalysis: analysis,
		ModelName:     config.ModelName,
		IsMultiTenant: config.MultiTenant,
	}

	funcMap := template.FuncMap{
		"ToLowerCase": func(s string) string {
			return strings.ToLower(s[:1]) + s[1:]
		},
	}

	t, err := template.New("tests").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return err
	}

	filename := filepath.Join(config.OutputDir, strings.ToLower(config.ModelName)+"_test.go")
	file, err := os.Create(filename) // #nosec G304 - filename is constructed from sanitized input in controlled directories
	if err != nil {
		return err
	}
	defer func() {
		if err := file.Close(); err != nil {
			fmt.Printf("Warning: failed to close file: %v\n", err)
		}
	}()

	return t.Execute(file, data)
}
