// Package cli provides the Lift CLI command implementations.
package cli

import (
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/pay-theory/lift/internal/liftconfig"
	"github.com/pay-theory/lift/internal/templates"
)

// NewCommandV2 implements the "lift new" command for Milestone 2+.
// It scaffolds a new Lift project using embedded templates.
type NewCommandV2 struct{}

func (c *NewCommandV2) Name() string        { return "new" }
func (c *NewCommandV2) Description() string { return "Create a new Lift project" }
func (c *NewCommandV2) Usage() string {
	return `lift new [<app>] --template <template> --base-domain <apex>

Flags:
  --template <name>       Template to use (default: basic-api)
  --base-domain <apex>    Base domain for the project (required for domain-enabled templates)
  --pt                    Generate Pay Theory devops assets (not yet implemented)

Examples:
  lift new my-app --base-domain example.com
  lift new --template basic-api --base-domain example.com`
}

// TemplateData contains the data passed to templates during rendering.
type TemplateData struct {
	AppName    string
	ModuleName string
	BaseDomain string
}

// Execute runs the new command with the provided arguments.
func (c *NewCommandV2) Execute(_ context.Context, args []string) error {
	// Parse arguments
	opts, err := c.parseArgs(args)
	if err != nil {
		return err
	}

	// If opts is nil, --help was printed
	if opts == nil {
		return nil
	}

	// Validate options
	if err := c.validateOpts(opts); err != nil {
		return err
	}

	// Determine target directory
	targetDir, err := c.resolveTargetDir(opts.appName)
	if err != nil {
		return err
	}

	// Check for existing lift.yaml
	if err := c.checkExistingProject(targetDir); err != nil {
		return err
	}

	// Scaffold the project
	if err := c.scaffold(targetDir, opts); err != nil {
		return err
	}

	// Print success message
	c.printSuccess(targetDir, opts.appName)

	return nil
}

// newOpts holds parsed command options.
type newOpts struct {
	appName    string
	template   string
	baseDomain string
	pt         bool
}

func (c *NewCommandV2) parseArgs(args []string) (*newOpts, error) {
	opts := &newOpts{
		template: "basic-api", // default
	}

	for i := 0; i < len(args); i++ {
		arg := args[i]

		switch {
		case arg == "--template" && i+1 < len(args):
			i++
			opts.template = args[i]
		case strings.HasPrefix(arg, "--template="):
			opts.template = strings.TrimPrefix(arg, "--template=")
		case arg == "--base-domain" && i+1 < len(args):
			i++
			opts.baseDomain = args[i]
		case strings.HasPrefix(arg, "--base-domain="):
			opts.baseDomain = strings.TrimPrefix(arg, "--base-domain=")
		case arg == "--help" || arg == "-h":
			fmt.Println(c.Usage())
			return nil, nil // Signal to caller to exit without error
		case arg == "--pt":
			opts.pt = true
		case strings.HasPrefix(arg, "-"):
			return nil, fmt.Errorf("unknown flag: %s\nUsage: %s", arg, c.Usage())
		default:
			// Positional argument (app name)
			if opts.appName == "" {
				opts.appName = arg
			} else {
				return nil, fmt.Errorf("unexpected argument: %s\nUsage: %s", arg, c.Usage())
			}
		}
	}

	return opts, nil
}

func (c *NewCommandV2) validateOpts(opts *newOpts) error {
	// Check --pt flag (stub for Milestone 6)
	if opts.pt {
		return fmt.Errorf("--pt flag is not yet implemented (Milestone 6)\n\nThe --pt flag will generate Pay Theory devops assets (buildspec.yml, shell/*).\nFor now, only GitHub Actions OIDC workflows are generated by default")
	}

	// Validate template
	if opts.template != "basic-api" {
		return fmt.Errorf("unknown template: %s\n\nAvailable templates:\n  - basic-api (default)", opts.template)
	}

	// Validate base-domain for domain-enabled templates
	if opts.baseDomain == "" {
		return fmt.Errorf("--base-domain is required for template %s\n\nExample: lift new my-app --base-domain example.com", opts.template)
	}

	return nil
}

func (c *NewCommandV2) resolveTargetDir(appName string) (string, error) {
	if appName == "" {
		// Bootstrap current directory
		cwd, err := os.Getwd()
		if err != nil {
			return "", fmt.Errorf("failed to get current directory: %w", err)
		}
		return cwd, nil
	}

	// Create new directory for the app
	absPath, err := filepath.Abs(appName)
	if err != nil {
		return "", fmt.Errorf("failed to resolve path %s: %w", appName, err)
	}

	// Check if directory already exists
	if info, err := os.Stat(absPath); err == nil {
		if info.IsDir() {
			return "", fmt.Errorf("directory %s already exists\n\nTo bootstrap an existing directory, cd into it and run: lift new --base-domain <apex>", appName)
		}
		return "", fmt.Errorf("path %s already exists and is not a directory", appName)
	}

	return absPath, nil
}

func (c *NewCommandV2) checkExistingProject(targetDir string) error {
	configPath := filepath.Join(targetDir, liftconfig.ConfigFileName)
	if _, err := os.Stat(configPath); err == nil {
		return fmt.Errorf("%s already exists in %s\n\nThis directory is already a Lift project. To re-scaffold, remove %s first",
			liftconfig.ConfigFileName, targetDir, liftconfig.ConfigFileName)
	}
	return nil
}

func (c *NewCommandV2) scaffold(targetDir string, opts *newOpts) error {
	// Determine app name if not provided
	appName := opts.appName
	if appName == "" {
		appName = filepath.Base(targetDir)
	}

	// Create template data
	data := TemplateData{
		AppName:    appName,
		ModuleName: appName, // Default module name to app name
		BaseDomain: opts.baseDomain,
	}

	// Create target directory if needed
	if err := os.MkdirAll(targetDir, 0750); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", targetDir, err)
	}

	// Walk the embedded template FS and render each file
	templateRoot := "basic-api"
	err := fs.WalkDir(templates.BasicAPIFS, templateRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// Get relative path from template root
		relPath, err := filepath.Rel(templateRoot, path)
		if err != nil {
			return err
		}

		// Skip root
		if relPath == "." {
			return nil
		}

		// Compute target path
		targetPath := filepath.Join(targetDir, relPath)

		// Strip .tmpl extension (TrimSuffix is a no-op if suffix not present)
		targetPath = strings.TrimSuffix(targetPath, ".tmpl")

		if d.IsDir() {
			// Create directory
			return os.MkdirAll(targetPath, 0750)
		}

		// Read and render template file
		content, err := templates.BasicAPIFS.ReadFile(path)
		if err != nil {
			return fmt.Errorf("failed to read template %s: %w", path, err)
		}

		// Parse and execute template
		rendered, err := c.renderTemplate(string(content), data)
		if err != nil {
			return fmt.Errorf("failed to render template %s: %w", path, err)
		}

		// Ensure parent directory exists
		if err := os.MkdirAll(filepath.Dir(targetPath), 0750); err != nil {
			return fmt.Errorf("failed to create directory for %s: %w", targetPath, err)
		}

		// Write file
		if err := os.WriteFile(targetPath, []byte(rendered), 0600); err != nil {
			return fmt.Errorf("failed to write %s: %w", targetPath, err)
		}

		return nil
	})

	if err != nil {
		return fmt.Errorf("failed to scaffold project: %w", err)
	}

	return nil
}

func (c *NewCommandV2) renderTemplate(content string, data TemplateData) (string, error) {
	tmpl, err := template.New("file").Parse(content)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (c *NewCommandV2) printSuccess(targetDir string, appName string) {
	name := appName
	if name == "" {
		name = filepath.Base(targetDir)
	}

	fmt.Printf("✅ Created Lift project: %s\n", name)
	fmt.Printf("📁 Location: %s\n", targetDir)
	fmt.Printf("\n")
	fmt.Printf("📁 Project structure:\n")
	fmt.Printf("   %s/\n", name)
	fmt.Printf("   ├── lift.yaml          # Project configuration\n")
	fmt.Printf("   ├── go.mod             # Go module\n")
	fmt.Printf("   ├── cmd/api/main.go    # Lambda entrypoint\n")
	fmt.Printf("   ├── cdk/               # CDK infrastructure\n")
	fmt.Printf("   │   ├── cdk.json\n")
	fmt.Printf("   │   ├── go.mod\n")
	fmt.Printf("   │   └── main.go\n")
	fmt.Printf("   └── .github/workflows/ # CI/CD\n")
	fmt.Printf("       ├── deploy.yml\n")
	fmt.Printf("       └── pr.yml\n")
	fmt.Printf("\n")
	fmt.Printf("🚀 Next steps:\n")
	if appName != "" {
		fmt.Printf("   cd %s\n", appName)
	}
	fmt.Printf("   go mod tidy\n")
	fmt.Printf("   lift up --stage dev\n")
	fmt.Printf("\n")
	fmt.Printf("📖 GitHub setup (for CI/CD):\n")
	fmt.Printf("   1. Create GitHub Environments: dev, staging, live\n")
	fmt.Printf("   2. Set environment variable: AWS_ROLE_ARN\n")
	fmt.Printf("   3. Set environment variable: AWS_REGION (recommended)\n")
}
